name: ci-fast

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  lint_typecheck_test:
    steps:
      - uses: eas/checkout
      - uses: eas/install_node_modules
      - name: Lint
        run: npm run lint
      - name: Typecheck
        run: npm run typecheck
      - name: Jest
        run: npm run test
