name: e2e-tests

on:
  pull_request_labeled:
    labels: ["run-e2e"]
  workflow_dispatch: {}

jobs:
  build_ios_for_e2e:
    type: build
    params:
      platform: ios
      profile: e2e-test

  build_android_for_e2e:
    type: build
    params:
      platform: android
      profile: e2e-test

  report:
    after: [build_ios_for_e2e, build_android_for_e2e]
    type: github-comment
